package com.example.hiciu.apptesting.DaoGenerated;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.hiciu.apptesting.DaoGenerated.loggedInEntity;

import com.example.hiciu.apptesting.DaoGenerated.loggedInEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig loggedInEntityDaoConfig;

    private final loggedInEntityDao loggedInEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        loggedInEntityDaoConfig = daoConfigMap.get(loggedInEntityDao.class).clone();
        loggedInEntityDaoConfig.initIdentityScope(type);

        loggedInEntityDao = new loggedInEntityDao(loggedInEntityDaoConfig, this);

        registerDao(loggedInEntity.class, loggedInEntityDao);
    }
    
    public void clear() {
        loggedInEntityDaoConfig.getIdentityScope().clear();
    }

    public loggedInEntityDao getLoggedInEntityDao() {
        return loggedInEntityDao;
    }

}
