package com.example.hiciu.apptesting.DaoGenerated;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LOGGED_IN_ENTITY.
 */
public class loggedInEntity {

    private Long id;
    private Boolean loggedIn;

    public loggedInEntity() {
    }

    public loggedInEntity(Long id) {
        this.id = id;
    }

    public loggedInEntity(Long id, Boolean loggedIn) {
        this.id = id;
        this.loggedIn = loggedIn;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getLoggedIn() {
        return loggedIn;
    }

    public void setLoggedIn(Boolean loggedIn) {
        this.loggedIn = loggedIn;
    }

}
